# Generated by Django 4.2.8 on 2023-12-19 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("static_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="user_hour_agg",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(blank=True, max_length=30, null=True)),
                ("hour", models.CharField(blank=True, max_length=30, null=True)),
                ("cnt", models.IntegerField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="USER_ID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "USER_HOUR_AGG",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="user_genre_agg",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(blank=True, max_length=30, null=True)),
                ("track_genre", models.CharField(blank=True, max_length=30, null=True)),
                ("cnt", models.IntegerField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="USER_ID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "USER_GENRE_AGG",
                "managed": True,
            },
        ),
    ]
