# Generated by Django 4.2.8 on 2023-12-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music_rec_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlisttrack",
            name="playback",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playlisttrack",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
