# Generated by Django 4.2.8 on 2023-12-14 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("music_rec_app", "0002_playlisttrack_playback_playlisttrack_score"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playlisttrack",
            old_name="score",
            new_name="rating",
        ),
    ]
