# Generated by Django 4.2.8 on 2023-12-18 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("music_rec_app", "0003_rename_score_playlisttrack_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playlisttrack",
            old_name="playback",
            new_name="cnt",
        ),
    ]
