# Generated by Django 4.2.8 on 2023-12-21 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("music_rec_app", "0004_rename_playback_playlisttrack_cnt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audiofeature",
            old_name="insrumentalness",
            new_name="instrumentalness",
        ),
    ]
