# Generated by Django 4.2.8 on 2023-12-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music_rec_app", "0005_rename_insrumentalness_audiofeature_instrumentalness"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofeature",
            name="gmm_cluster",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audiofeature",
            name="pca_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audiofeature",
            name="pca_y",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
