# Generated by Django 4.2.8 on 2023-12-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music_rec_app", "0007_korea_top50_artist_korea_top50_track_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="korea_top50_track",
            name="rank",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
